import turtle
t = turtle.Turtle()
def drawT(startx, starty):
    t.penup()
    t.goto(startx, starty)
    t.setheading(0)
    t.pendown()
    t.fillcolor("lightblue")
    t.begin_fill()
    t.forward(100)
    t.right(90)
    t.forward(15)
    t.right(90)
    t.forward(40)
    t.left(90)
    t.forward(85)
    t.right(90)
    t.forward(20)
    t.right(90)
    t.forward(85)
    t.left(90)
    t.forward(40)
    t.right(90)
    t.forward(15)
    t.end_fill()

t = turtle.Turtle()
t.pensize(5)   

turtle.done()