import turtle
n = 1.5
turtle.width(2)
turtle.circle(100*n)
turtle.left(90)
turtle.penup()
turtle.forward(150*n)
turtle.left(90)
turtle.forward(55*n)
turtle.pendown()
turtle.left(90)
turtle.forward(50*n)
turtle.circle(20*n,180)
turtle.forward(50*n)
turtle.right(90)
turtle.penup()
turtle.forward(10*n)
turtle.pendown()
turtle.right(90)
turtle.forward(70*n)
turtle.right(180)
turtle.forward(70*n)
turtle.right(155)
turtle.forward(77*n)
turtle.left(155)
turtle.forward(70*n)
turtle.right(90)
turtle.penup()
turtle.forward(15*n)
turtle.pendown()
turtle.right(90)
turtle.forward(70*n)
turtle.left(180)
turtle.forward(70*n)
turtle.right(90)
turtle.penup()
turtle.forward(44*n)
turtle.pendown()
turtle.forward(16*n)
turtle.right(10)
turtle.forward(20*n)
turtle.circle(-30*n,150)
turtle.forward(10*n)
turtle.right(5)
turtle.circle(-500*n,27)
turtle.right(5)
turtle.forward(10*n)
turtle.circle(-30*n,150)
turtle.forward(12*n)
turtle.right(10)
turtle.forward(22*n)




turtle.penup()
turtle.left(90)
turtle.forward(500*n)
turtle.pendown()